name: Java CI to create and upload release
on:
  push:
    branches: [ "main" ]

env:
  build-number: ${GITHUB_RUN_NUMBER}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - run: echo  env.build-number }}
      - run: mvn clean package -DskipTests
      - run: mkdir staging && mv target/jwt-demo-0.0.1-SNAPSHOT.jar target/jwt-demo-0.0.1-${{ env.build-number }}.jar && cp target/*.jar staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
          retention-days: 1
