name: Java CI to create and upload release
on:
  push:
    branches: ["main"]

env:
  version: ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"

      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Output Run Number
        run: echo ${{ github.run_number }}
      - name: Output Run Attempt
        run: echo ${{ github.run_attempt }}

      - name: Display Version
        run: echo ${{ env.version }}

      - run: mvn clean package -DskipTests
      - run: mkdir staging && mv target/jwt-demo-0.0.1-SNAPSHOT.jar target/jwt-demo-0.0.1-${{ env.version }}.jar && cp target/*.jar staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging/jwt-demo-0.0.1-${{ env.version }}.jar
          retention-days: 1
